import './globals.css'
import type { Metadata } from 'next'
import { Playfair_Display, Montserrat } from 'next/font/google'
import Navbar from './Navbar';

export const playfair = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700", "800", "900" ],
  variable: "--font-playfair"
 });

export const montseratt = Montserrat({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700", "800", "900" ],
  variable: "--font-montserrat"
 });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montseratt.className} relative`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
